export const FETCH_USER = 'FETCH_USER';
export const SEND_MAIL = 'SEND_MAIL';
export const CREATE_USER = 'CREATE_USER';
export const SAVE_ACTIVITY = 'SAVE_ACTIVITY';

export const TOGGLE_ACTIVE = 'TOGGLE_ACTIVE';
export const EMBED_STREAM = 'EMBED_STREAM';
export const FETCH_FEATURED_REQUEST = 'FETCH_FEATURED_REQUEST';
export const FETCH_FEATURED_SUCCESS = 'FETCH_FEATURED_SUCCESS';
export const FETCH_FEATURED_FAILURE = 'FETCH_FEATURED_FAILURE';
export const FETCH_TOPGAMES_REQUEST = 'FETCH_TOPGAMES_REQUEST';
export const FETCH_TOPGAMES_SUCCESS = 'FETCH_TOPGAMES_SUCCESS';
export const FETCH_TOPGAMES_FAILURE = 'FETCH_TOPGAMES_FAILURE';
export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE';
export const FETCH_DASHBOARD = 'FETCH_DASHBOARD';
export const FETCH_BROADCASTERS = 'FETCH_BROADCASTERS';
export const FETCH_GAMES = 'FETCH_GAMES';
export const FETCH_DASHBOARD_FAILURE = 'FETCH_DASHBOARD_FAILURE';
export const FETCH_CLIPS = 'FETCH_CLIPS';

// AUTH types
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
